export interface PseStock {
  symbol: string;
  name: string;
}

export const PSE_STOCKS: PseStock[] = [
  { symbol: "AC", name: "Ayala Corporation" },
  { symbol: "ACEN", name: "ACEN Corporation" },
  { symbol: "AEV", name: "Aboitiz Equity Ventures, Inc." },
  { symbol: "AGI", name: "Alliance Global Group, Inc." },
  { symbol: "AGP", name: "AG&P International Holdings Corp" },
  { symbol: "ABA", name: "Alliance Bank Philippines Corp" },
  { symbol: "ALCO", name: "Alcorn Gold Resources Corp" },
  { symbol: "ALI", name: "Ayala Land, Inc." },
  { symbol: "ANS", name: "A. Soriano Corporation" },
  { symbol: "AP", name: "Aboitiz Power Corporation" },
  { symbol: "APL", name: "Appleone Properties, Inc." },
  { symbol: "APO", name: "Apo Land and Timber Corp" },
  { symbol: "AR", name: "Asia Amalgamated Holdings Corp" },
  { symbol: "AREIT", name: "AREIT, Inc." },
  { symbol: "ATI", name: "Asian Terminals, Inc." },
  { symbol: "ATN", name: "A&T Industries Corp" },
  { symbol: "BDO", name: "BDO Unibank, Inc." },
  { symbol: "BEL", name: "Belle Corporation" },
  { symbol: "BPI", name: "Bank of the Philippine Islands" },
  { symbol: "BRN", name: "Basic Resources International" },
  { symbol: "BSC", name: "Basic Holdings Corp" },
  { symbol: "CBC", name: "Cement Corp of the Philippines" },
  { symbol: "CEU", name: "Centro Escolar University" },
  { symbol: "CHIB", name: "China Banking Corporation" },
  { symbol: "CLI", name: "Cebu Landmasters, Inc." },
  { symbol: "CNPF", name: "Century Pacific Food, Inc." },
  { symbol: "CNVRG", name: "Converge ICT Solutions, Inc." },
  { symbol: "COL", name: "COL Financial Group, Inc." },
  { symbol: "COSCO", name: "Cosco Capital, Inc." },
  { symbol: "CHP", name: "Cemex Holdings Philippines, Inc." },
  { symbol: "CPG", name: "Century Properties Group, Inc." },
  { symbol: "DITO", name: "DITO CME Holdings Corp" },
  { symbol: "DMC", name: "DMCI Holdings, Inc." },
  { symbol: "DNL", name: "D&L Industries, Inc." },
  { symbol: "EEI", name: "EEI Corporation" },
  { symbol: "EMP", name: "Emperador Inc." },
  { symbol: "EW", name: "East West Banking Corporation" },
  { symbol: "EVER", name: "Ever Bilena Cosmetics, Inc." },
  { symbol: "FB", name: "FB Holdings, Inc." },
  { symbol: "FGEN", name: "First Gen Corporation" },
  { symbol: "FLI", name: "Filinvest Land, Inc." },
  { symbol: "FNI", name: "Global Ferronickel Holdings, Inc." },
  { symbol: "GLO", name: "Globe Telecom, Inc." },
  { symbol: "GMA7", name: "GMA Network, Inc." },
  { symbol: "GSMI", name: "Ginebra San Miguel, Inc." },
  { symbol: "GTCAP", name: "GT Capital Holdings, Inc." },
  { symbol: "HI", name: "House of Investments, Inc." },
  { symbol: "ICT", name: "International Container Terminal Services, Inc." },
  { symbol: "IMI", name: "Integrated Micro-Electronics, Inc." },
  { symbol: "IS", name: "I-Remit, Inc." },
  { symbol: "JFC", name: "Jollibee Foods Corporation" },
  { symbol: "JGS", name: "JG Summit Holdings, Inc." },
  { symbol: "KEP", name: "Keppel Philippines Properties" },
  { symbol: "LPZ", name: "Lopez Holdings Corporation" },
  { symbol: "LTG", name: "LT Group, Inc." },
  { symbol: "MA", name: "MacroAsia Corporation" },
  { symbol: "MAXS", name: "Max's Group, Inc." },
  { symbol: "MBT", name: "Metropolitan Bank & Trust Company" },
  { symbol: "MEG", name: "Megaworld Corporation" },
  { symbol: "MER", name: "Manila Electric Company (Meralco)" },
  { symbol: "MWIDE", name: "Megawide Construction Corporation" },
  { symbol: "MHC", name: "Manila Hotel Corporation" },
  { symbol: "MONDE", name: "Monde Nissin Corporation" },
  { symbol: "MPI", name: "Metro Pacific Investments Corporation" },
  { symbol: "MREIT", name: "Megaworld REIT, Inc." },
  { symbol: "MRSGI", name: "Metro Retail Stores Group, Inc." },
  { symbol: "NIKL", name: "Nickel Asia Corporation" },
  { symbol: "NOW", name: "Now Telecom Company, Inc." },
  { symbol: "ORE", name: "Oriental Peninsula Resources Group, Inc." },
  { symbol: "PBC", name: "Philippine Business Bank" },
  { symbol: "PBB", name: "Philippine Business Bank (Series A)" },
  { symbol: "PCOR", name: "Petron Corporation" },
  { symbol: "PGOLD", name: "Puregold Price Club, Inc." },
  { symbol: "PIZZA", name: "Shakey's Pizza Asia Ventures, Inc." },
  { symbol: "PNB", name: "Philippine National Bank" },
  { symbol: "PNX", name: "Phinma Corporation" },
  { symbol: "PORT", name: "Asian Terminals, Inc. (Preferreds)" },
  { symbol: "PSE", name: "The Philippine Stock Exchange, Inc." },
  { symbol: "PSB", name: "Philippine Savings Bank" },
  { symbol: "RCB", name: "Rizal Commercial Banking Corporation" },
  { symbol: "RCR", name: "RL Commercial REIT, Inc." },
  { symbol: "RFM", name: "RFM Corporation" },
  { symbol: "RLC", name: "Robinsons Land Corporation" },
  { symbol: "RRHI", name: "Robinsons Retail Holdings, Inc." },
  { symbol: "SCC", name: "Semirara Mining and Power Corporation" },
  { symbol: "SECB", name: "Security Bank Corporation" },
  { symbol: "SHLPH", name: "Shell Philippines Exploration B.V." },
  { symbol: "SLF", name: "Sun Life Financial Philippines" },
  { symbol: "SM", name: "SM Investments Corporation" },
  { symbol: "SMC", name: "San Miguel Corporation" },
  { symbol: "SMPH", name: "SM Prime Holdings, Inc." },
  { symbol: "SPC", name: "SPC Power Corporation" },
  { symbol: "SSI", name: "SSI Group, Inc." },
  { symbol: "STI", name: "STI Education Systems Holdings, Inc." },
  { symbol: "TC", name: "Trans-Asia Oil and Energy Development Corp" },
  { symbol: "TEL", name: "PLDT Inc." },
  { symbol: "UBP", name: "Union Bank of the Philippines" },
  { symbol: "URC", name: "Universal Robina Corporation" },
  { symbol: "VLL", name: "Vista Land & Lifescapes, Inc." },
  { symbol: "VMC", name: "Victorias Milling Company, Inc." },
  { symbol: "WLCON", name: "Wilcon Depot, Inc." },
  { symbol: "WIN", name: "Winterless Inc" },
  { symbol: "2GO", name: "2GO Group, Inc." },
  { symbol: "ABG", name: "Abacus Consolidated Resources and Holdings, Inc." },
  { symbol: "ABS", name: "ABS-CBN Corporation" },
  { symbol: "ACEX", name: "Acesite (Phils.) Hotel Corporation" },
  { symbol: "ACM", name: "ACMDC Corp" },
  { symbol: "ACNB", name: "Amalgamated Commercial & Industrial Corp" },
  { symbol: "ACS", name: "Atrium Holdings Corp" },
  { symbol: "AGIN", name: "Agricultural Financial Corp" },
  { symbol: "AIC", name: "AIC Gold and General Mines, Inc." },
  { symbol: "ALHI", name: "Asian Life and General Assurance Corp" },
  { symbol: "ALPHA", name: "Alpha Securities Corp" },
  { symbol: "ALSA", name: "Alphaland Corporation" },
  { symbol: "AMA", name: "AMA Education System Holdings, Inc." },
  { symbol: "AMTI", name: "Amoranto Industries, Inc." },
  { symbol: "ANI", name: "Anglo Philippine Holdings Corporation" },
  { symbol: "AON", name: "AO Nova Corporation" },
  { symbol: "APEX", name: "Apex Mining Company, Inc." },
  { symbol: "APX", name: "Alsons Consolidated Resources, Inc." },
  { symbol: "ARC", name: "Arc Equity Corporation" },
  { symbol: "ARE", name: "Araneta Properties, Inc." },
  { symbol: "ARIA", name: "Aria Corporation" },
  { symbol: "ARM", name: "ARM Holdings Corp" },
  { symbol: "ARO", name: "Aboitiz InfraCapital, Inc." },
  { symbol: "ARS", name: "ASEAN China Resources Corp" },
  { symbol: "ART", name: "Arte Realizations Corp" },
  { symbol: "ARTK", name: "Arthaland Corporation" },
  { symbol: "ASB", name: "ASB Holdings, Inc." },
  { symbol: "ASCII", name: "Concrete Aggregates Corporation" },
  { symbol: "ASGN", name: "Asian Alliance Holdings Corp" },
  { symbol: "AWC", name: "Asian Wellness Corporation" },
  { symbol: "AXL", name: "Axelum Resources Corp" },
  { symbol: "BKR", name: "Bakker Land Corp" },
  { symbol: "BLNK", name: "BM Inland Gulf Properties Corp" },
  { symbol: "BMM", name: "B.M. Manalac Enterprises, Inc." },
  { symbol: "BPDO", name: "BDO Life Assurance Company" },
  { symbol: "C", name: "Crown Equities, Inc." },
  { symbol: "CA", name: "China Aviation Holdings Corp" },
  { symbol: "CAL", name: "Cal-Comp Technology (Philippines) Inc." },
  { symbol: "CASA", name: "Casatex Holdings, Inc." },
  { symbol: "CATL", name: "Catalunan Grandes Development Corp" },
  { symbol: "CDFI", name: "Casas & Associates Holding Inc." },
  { symbol: "CEI", name: "Centro Escolar Investment Corp" },
  { symbol: "CHAR", name: "Charoen Pokphand Foods (Philippine) Corp" },
  { symbol: "CLC", name: "Crown Lands Corp" },
  { symbol: "CMT", name: "Chemrez Technologies, Inc." },
  { symbol: "COAL", name: "Crown Asia Chemicals Corp" },
  { symbol: "CROWN", name: "Crown Asia Chemicals Corp" },
  { symbol: "DA", name: "DM Wenceslao & Associates Inc." },
  { symbol: "DAV", name: "Davao Union Cement Corporation" },
  { symbol: "DDC", name: "DoubleDragon Corporation" },
  { symbol: "DFNN", name: "DFNN, Inc." },
  { symbol: "DIZON", name: "Dizon Copper-Silver Mines, Inc." },
  { symbol: "DPTR", name: "DD-Meridian Park Development Corp" },
  { symbol: "ECP", name: "ECP Holdings Corp" },
  { symbol: "EDC", name: "Energy Development Corporation" },
  { symbol: "EEI", name: "EEI Corporation" },
  { symbol: "EIB", name: "Export and Industry Bank, Inc." },
  { symbol: "EJCP", name: "EJ Chua Portfolio Holdings Corp" },
  { symbol: "ELF", name: "Elixir Mining Corp" },
  { symbol: "FDC", name: "Filinvest Development Corporation" },
  { symbol: "FED", name: "Federal Resources Investment Group Inc" },
  { symbol: "FILRT", name: "Filinvest REIT Corp" },
  { symbol: "FINL", name: "STI Holdings, Inc." },
  { symbol: "FJP", name: "Forum Pacific, Inc." },
  { symbol: "FMETF", name: "First Metro Philippine Equity Exchange Traded Fund" },
  { symbol: "FPH", name: "First Philippine Holdings Corporation" },
  { symbol: "FRUIT", name: "Balintawak Holdings Corp" },
  { symbol: "GEO", name: "GeoCorp Mining Corp" },
  { symbol: "GEOGRACE", name: "Geograce Resources Philippines, Inc." },
  { symbol: "GERI", name: "Global-Estate Resorts, Inc." },
  { symbol: "GHI", name: "GoldRiver Holdings Inc" },
  { symbol: "GMR", name: "Greenergy Holdings Corp" },
  { symbol: "GSUN", name: "Goldstar Energy Corp" },
  { symbol: "H2O", name: "H2O Ventures Holdings Corp" },
  { symbol: "IDC", name: "Integrated Capital Equities Corp" },
  { symbol: "ION", name: "ION Holdings Corp" },
  { symbol: "IP", name: "IntegralPower Corp" },
  { symbol: "IPVG", name: "iPeople, Inc." },
  { symbol: "IRC", name: "IRC Properties Corp" },
  { symbol: "IS", name: "I-Remit, Inc." },
  { symbol: "ISM", name: "ISM Communications Corporation" },
  { symbol: "JAS", name: "Jasper Resources Corp" },
  { symbol: "JGS", name: "JG Summit Holdings, Inc." },
  { symbol: "JMA", name: "JMA Holdings Corp" },
  { symbol: "JOH", name: "J.G. Summit Petrochemical Corp" },
  { symbol: "JPA", name: "Jomasao Products Inc" },
  { symbol: "KPH", name: "Keppel Philippines Marine Inc" },
  { symbol: "LAND", name: "Landbank Financial Corporation" },
  { symbol: "LBC", name: "LBC Express Holdings, Inc." },
  { symbol: "LC", name: "Liberty Flour Mills, Inc." },
  { symbol: "LCB", name: "Life Corp of the Philippines" },
  { symbol: "LFM", name: "Liberty Flour Mills, Inc." },
  { symbol: "LIHC", name: "LBC Holdings Corp" },
  { symbol: "LMG", name: "Lorenzo Multi-Media Corp" },
  { symbol: "LR", name: "Leisure Resorts Concepts" },
  { symbol: "LSC", name: "Limketkai Development Corporation" },
  { symbol: "MACAY", name: "Macay Holdings, Inc." },
  { symbol: "MAH", name: "Malampaya Energy Corp" },
  { symbol: "MBC", name: "Music Broadcasting Corp" },
  { symbol: "MBT", name: "Metropolitan Bank & Trust Company" },
  { symbol: "MC", name: "Manila Corporation" },
  { symbol: "MCP", name: "Mancor Consolidated Resources Corp" },
  { symbol: "MED", name: "Medco Holdings, Inc." },
  { symbol: "MFIN", name: "Mapfre Insular Insurance Corp" },
  { symbol: "MHC", name: "Manila Hotel Corporation" },
  { symbol: "MJC", name: "MJC Investments Corp" },
  { symbol: "MM", name: "Marino Mart Inc" },
  { symbol: "MNC", name: "MNC Group, Inc." },
  { symbol: "MRC", name: "MRC Allied Industries" },
  { symbol: "MTG", name: "MTG Mining Corp" },
  { symbol: "NLEX", name: "North Luzon Expressway Corp" },
  { symbol: "NOW", name: "Now Telecom Company, Inc." },
  { symbol: "OPM", name: "Opus Mining Inc" },
  { symbol: "PACS", name: "PAC Holdings Corp" },
  { symbol: "PAX", name: "PAX Corp" },
  { symbol: "PBB", name: "Philippine Business Bank" },
  { symbol: "PHA", name: "ASEAN Construction & Dev Corp" },
  { symbol: "PHN", name: "Philippine National Bank (Preferreds)" },
  { symbol: "PLC", name: "Phil. Long Distance Telephone (Preferreds)" },
  { symbol: "PNX4", name: "Phinma Corporation (Preferred)" },
  { symbol: "PSEI", name: "PSEi Tracker Fund" },
  { symbol: "REIT", name: "RL Commercial REIT, Inc." },
  { symbol: "RJP", name: "Riverbanks Development Corp" },
  { symbol: "SGI", name: "Strong Group Inc" },
  { symbol: "SLI", name: "Sterling Land Holdings, Inc." },
  { symbol: "SOC", name: "Social Security System" },
  { symbol: "SPM", name: "St. Peter Life Plan, Inc." },
  { symbol: "SRN", name: "Siren Holdings Corp" },
  { symbol: "SRS", name: "Smart Renewable Systems Corp" },
  { symbol: "T", name: "Time Entertainment Holdings" },
  { symbol: "TAMC", name: "Trade Asset Management Corp" },
  { symbol: "TBC", name: "Tanay Resources Corporation" },
  { symbol: "TBGI", name: "Tabet Marketing Corp" },
  { symbol: "TLB", name: "TeleCommunity Financial Corp" },
  { symbol: "TPC", name: "Talon Petroleum Corp" },
  { symbol: "TPI", name: "Thor Precision Inc" },
  { symbol: "T2", name: "T2 Holdings Corp" },
  { symbol: "UEZ", name: "United Pulp and Paper Co., Inc." },
  { symbol: "UPI", name: "UPCC Inc" },
  { symbol: "URCB", name: "Universal Robina Corp (Preferred)" },
  { symbol: "WIN", name: "Wondershare Technology Group Co. Ltd" },
  { symbol: "X", name: "Xurpas Inc." },
  { symbol: "ZHI", name: "Zeus Holdings, Inc." },
];

export function searchPseStocks(query: string): PseStock[] {
  if (!query || query.length < 1) return PSE_STOCKS.slice(0, 20);
  const q = query.toLowerCase().trim();
  const exact: PseStock[] = [];
  const prefix: PseStock[] = [];
  const contains: PseStock[] = [];

  for (const s of PSE_STOCKS) {
    const sym = s.symbol.toLowerCase();
    const name = s.name.toLowerCase();
    if (sym === q) { exact.push(s); continue; }
    if (sym.startsWith(q) || name.startsWith(q)) { prefix.push(s); continue; }
    if (sym.includes(q) || name.includes(q)) contains.push(s);
  }

  return [...exact, ...prefix, ...contains].slice(0, 15);
}
